@echo off
echo Running config-test.json with debug logging...
call gradlew.bat runApp --args="analyze --project-path ./src --config ./config-test.json" -Dlogging.level.com.documentor.config=DEBUG -Dlogging.level.com.documentor.service=DEBUG
