# TestConfig Class Diagram

```mermaid
---
title: sample title
config: 
  layout: elk
  theme: forest %% neutral, for black-and-white documents commented out
---
classDiagram
    class TestConfig {
    }

```

Generated on: 2025-10-20T05:54:19.646727100
