# LlmModelTypeDetector Class Diagram

```mermaid
---
title: LlmModelTypeDetector_diagram.mmd
config: 
  layout: elk
  theme: forest %% neutral, for black-and-white documents commented out
---
classDiagram
    class LlmModelTypeDetector {
    }

```

Generated on: 2025-12-08T17:26:47.974593500
